# Generated by Django 4.0.6 on 2022-07-06 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SongLog',
            fields=[
                ('url', models.URLField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=1000)),
                ('duration', models.CharField(max_length=8)),
                ('thumbnail', models.ImageField(upload_to='')),
            ],
        ),
    ]
