# Generated by Django 4.0.6 on 2022-07-07 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songlog',
            name='duration',
            field=models.FloatField(),
        ),
    ]
