# Generated by Django 4.0.6 on 2022-07-12 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_bot', '0002_alter_songlog_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songlog',
            name='thumbnail',
            field=models.ImageField(max_length=225, upload_to=''),
        ),
    ]
